### ISSUE TITLE
getQRCodeImage(): Return value must be of type string, bool returned

### ISSUE THREAD

**Issue by shirakun** [RobThree/TwoFactorAuth#129]
"version": "v2.1.0",

```
use RobThree\Auth\TwoFactorAuth;

....

$tfa  = new TwoFactorAuth();
$secret = $tfa->createSecret();
$qr     = $tfa->getQRCodeImageAsDataUri(config('app.name', 'Paymenter') . '-' . $user->email, $secret);

```

```
2024-05-05 08:06:12 - error - RobThree\Auth\Providers\Qr\QRServerProvider::getQRCodeImage(): Return value must be of type string, bool returned
#0 /home/localhos/domains/localhost.lan/vendor/robthree/twofactorauth/lib/TwoFactorAuth.php(120): RobThree\Auth\Providers\Qr\QRServerProvider->getQRCodeImage()
#1 /home/localhos/domains/localhost.lan/app/Http/Controllers/Clients/HomeController.php(40): RobThree\Auth\TwoFactorAuth->getQRCodeImageAsDataUri()
#2 /home/localhos/domains/localhost.lan/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\Http\Controllers\Clients\HomeController->profile()
#3 /home/localhos/domains/localhost.lan/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\Routing\Controller->callAction()
#4 /home/localhos/domains/localhost.lan/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\Routing\ControllerDispatcher->dispatch()
#5 /home/localhos/domains/localhost.lan/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\Routing\Route->runController()
#6 /home/localhos/domains/localhost.lan/vendor/laravel/framework/src/Illuminate/Routing/Router.php(806): Illuminate\Routing\Route->run()
#7 /home/localhos/domains/localhost.lan/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#8 /home/localhos/domains/localhost.lan/vendor/laravel/framework/src/Illuminate/Auth/Middleware/RequirePassword.php(84): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#9 /home/localhos/domains/localhost.lan/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Auth\Middleware\RequirePassword->handle()
#10 /home/localhos/domains/localhost.lan/app/Http/Middleware/SetLocale.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#11 /home/localhos/domains/localhost.lan/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\Http\Middleware\SetLocale->handle()
#12 /home/localhos/domains/localhost.lan/app/Http/Middleware/MustVerifyEmail.php(17): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#13 /home/localhos/domains/localhost.lan/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\Http\Middleware\MustVerifyEmail->handle()
#14 /home/localhos/domains/localhost.lan/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#15 /home/localhos/domains/localhost.lan/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Routing\Middleware\SubstituteBindings->handle()
#16 /home/localhos/domains/localhost.lan/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#17 /home/localhos/domains/localhost.lan/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Auth\Middleware\Authenticate->handle()
#18 /home/localhos/domains/localhost.lan/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#19 /home/localhos/domains/localhost.lan/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()
#20 /home/localhos/domains/localhost.lan/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#21 /home/localhos/domains/localhost.lan/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#22 /home/localhos/domains/localhost.lan/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#23 /home/localhos/domains/localhost.lan/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest()
#24 /home/localhos/domains/localhost.lan/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Session\Middleware\StartSession->handle()
#25 /home/localhos/domains/localhost.lan/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#26 /home/localhos/domains/localhost.lan/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#27 /home/localhos/domains/localhost.lan/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#28 /home/localhos/domains/localhost.lan/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#29 /home/localhos/domains/localhost.lan/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#30 /home/localhos/domains/localhost.lan/vendor/laravel/framework/src/Illuminate/Routing/Router.php(805): Illuminate\Pipeline\Pipeline->then()
#31 /home/localhos/domains/localhost.lan/vendor/laravel/framework/src/Illuminate/Routing/Router.php(784): Illuminate\Routing\Router->runRouteWithinStack()
#32 /home/localhos/domains/localhost.lan/vendor/laravel/framework/src/Illuminate/Routing/Router.php(748): Illuminate\Routing\Router->runRoute()
#33 /home/localhos/domains/localhost.lan/vendor/laravel/framework/src/Illuminate/Routing/Router.php(737): Illuminate\Routing\Router->dispatchToRoute()
#34 /home/localhos/domains/localhost.lan/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\Routing\Router->dispatch()
#35 /home/localhos/domains/localhost.lan/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#36 /home/localhos/domains/localhost.lan/vendor/livewire/livewire/src/Features/SupportDisablingBackButtonCache/DisableBackButtonCacheMiddleware.php(19): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#37 /home/localhos/domains/localhost.lan/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Livewire\Features\SupportDisablingBackButtonCache\DisableBackButtonCacheMiddleware->handle()
#38 /home/localhos/domains/localhost.lan/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#39 /home/localhos/domains/localhost.lan/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle()
#40 /home/localhos/domains/localhost.lan/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#41 /home/localhos/domains/localhost.lan/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#42 /home/localhos/domains/localhost.lan/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle()
#43 /home/localhos/domains/localhost.lan/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#44 /home/localhos/domains/localhost.lan/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#45 /home/localhos/domains/localhost.lan/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Foundation\Http\Middleware\TrimStrings->handle()
#46 /home/localhos/domains/localhost.lan/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#47 /home/localhos/domains/localhost.lan/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle()
#48 /home/localhos/domains/localhost.lan/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(99): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#49 /home/localhos/domains/localhost.lan/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#50 /home/localhos/domains/localhost.lan/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#51 /home/localhos/domains/localhost.lan/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Http\Middleware\HandleCors->handle()
#52 /home/localhos/domains/localhost.lan/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#53 /home/localhos/domains/localhost.lan/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Http\Middleware\TrustProxies->handle()
#54 /home/localhos/domains/localhost.lan/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#55 /home/localhos/domains/localhost.lan/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\Pipeline\Pipeline->then()
#56 /home/localhos/domains/localhost.lan/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#57 /home/localhos/domains/localhost.lan/public/index.php(51): Illuminate\Foundation\Http\Kernel->handle()
#58 {main}

```

```

php -v
PHP 8.2.13 (cli) (built: Nov 22 2023 16:06:20) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.13, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.13, Copyright (c), by Zend Technologies

php -m
[PHP Modules]
bcmath
bz2
calendar
clos_ssa
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
geoip
gettext
gmagick
gmp
hash
i360
iconv
imap
intl
json
libxml
mbstring
mcrypt
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
random
readline
Reflection
session
shmop
SimpleXML
soap
sockets
sodium
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlrpc
xmlwriter
xsl
yaml
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

```

**Comment by willpower232** [comment]
If you aren't specifying the QR code provider then it will be using the default [QRServerProvider](https://github.com/RobThree/TwoFactorAuth/blob/master/lib/Providers/Qr/QRServerProvider.php) so I imagine that there was a curl error between yourselves and api.qrserver.com, unfortunately the code should be handling it better but isn't.

You might wish to switch to an offline QR code provider like Bacon or Endroid.

@NicolasCARPi @RobThree I presume the best fix is for [getContent](https://github.com/RobThree/TwoFactorAuth/blob/f5eb9a7051e71297585d1fb5e6c72e9f18c00cd2/lib/Providers/Qr/BaseHTTPQRCodeProvider.php#L11) to throw an exception if it gets a bool back from curl rather than forcing the other four providers to throw their own exceptions?

The migration path to V3 isn't super advanced so I have no issue with not backporting the fix to V2 unless you really want to maintain a V2 branch at this point now that the V3 changes are in the primary branch.

**Comment by NicolasCARPi** [comment]
Yeah, handling curl errors in this basehttp class seems the right way to go. And then it can only return string or throw exception. I guess it can simply be something like:

~~~php
 $data = curl_exec($curlhandle);
if ($data === false) {
     throw new WhateverException(curl_error($curlhandle));
}
~~~
